name: Run PQC_Assessment_Tool

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  run-pqc-assessment:
    runs-on: self-hosted

    steps:
      - name: Use PQC_Assessment Runner Action
        uses: AppViewX-Inc-PE/assessment-tool@main
        with:
          target-repo-url: ${{ github.repository }}
