name: Run PQC_Assessment_Tool

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - PQC-V2

jobs:
  run-pqc-assessment:
    runs-on: self-hosted

    steps:
      # Debug: Verify the secret is accessible
      - name: Debug - Check Secret
        run: |
          if [ -z "${{ secrets.PQC_PAT_TOKEN }}" ]; then
            echo "Error: PQC_PAT_TOKEN secret is missing or empty!"
            exit 1
          else
            echo "PQC_PAT_TOKEN secret is available."
          fi
        shell: bash

      # Debug: Verify repository access using the PAT
      - name: Debug - Check Repository Access
        run: |
          echo "Checking access to rahul-m21/Test_Tool..."
          curl -s -H "Authorization: token ${{ secrets.PQC_PAT_TOKEN }}" \
            https://api.github.com/repos/rahul-m21/Test_Tool | jq .name
        shell: bash

      # Main step: Use the PQC_Assessment Runner Action
      - name: Use PQC_Assessment Runner Action
        uses: rahul-m21/Test_Tool@v2.0.0
        with:
          target-repo-url: ${{ github.repository }}
          token: ${{ secrets.PQC_PAT_TOKEN }}  # Use PAT for authentication