name: Run PQC_Assessment_Tool

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - PQC-V2

jobs:
  run-pqc-assessment:
    runs-on: self-hosted

    steps:
      - name: Use PQC_Assessment Runner Action
        uses: rahul-m21/Test_Tool@v2.0.0
        with:
          target-repo-url: ${{ github.repository }}
          token: ${{ secrets.PQC_PAT_TOKEN }}  # Use PAT for authentication