name: Run PQC_Assessment_Tool

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - docker

jobs:
  run-pqc-assessment:
    runs-on: self-hosted

    steps:
      - name: Use PQC_Assessment Runner Action
        uses: rahul-avx/assessment-tool-pipeline@main
        with:
          target-repo-url: ${{ github.repository }}
